### ISSUE TITLE
jump into his own folder when someone login in with rest framework authentication 

### ISSUE THREAD

**Issue by huarda** [meteozond/djangodav#36]
I want to redirect the his own folder which someone login in with rest framework authentication

any ideas?

**Comment by huarda** [comment]
What I am currently doing is to set the root directory of each user dynamically

**Comment by meteozond** [comment]
It is quite complicated. As I see you are not able to show different listings and files for different users at the moment, because they are getting just before authorisation with the different abstraction layers. It is more consistent to provide different resources for each user, at least because http resource structure expects uniq url provided for each resource.
