### ISSUE TITLE
Cannot upload file via webdav client!

### ISSUE THREAD

**Issue by huarda** [meteozond/djangodav#37]
while use forklift to upload files ,it cannot do it

It returns "# Could not read status line: connection timed out"

**Comment by huarda** [comment]
When I test with winscp. It can work

So it is forklift's bug?

**Comment by meteozond** [comment]
Unfortunately official webdav specification got a lot of gaps which client developers interpret in a wide range of ways. We tried to make it compatible with most of them (windows and mac clients were the most painful), but not ForkLift. I've created feature request #39. We will try to check this out weather it could be implemented. Can't say it is going to be in the nearest future due to lack of resources.
